# SPDX-FileCopyrightText: 2025 Thiago S. R. Silva, Diego S. Porto
# SPDX-License-Identifier: MIT

version: "3.9"

services:
  rdf-generator:
    build: .
    container_name: rdf-generator
    volumes:
      # Mount input data folder
      - ./data:/app/data
      # Mount outputs folder so results persist on host
      - ./outputs:/app/outputs
      # Mount configuration file
      - ./configs/config.yaml:/app/config.yaml
    environment:
      - ENV=production
    command: ["python", "rdf_generator/main.py"]

